In [4]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np


plt.style.use("fivethirtyeight")

In [17]:
class Perceptron:
    def __init__(self, eta:float=None, epochs:int=None):
        self.weight = np.random.randn(3) * 1e-4
        self.eta = eta #Learning rate
        self.epochs = epochs #Iterations
        
    def fit(self, X, y):
        self.X=X
        self.y=y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
        print(f"x with bias: \n{X_with_bias}")

In [18]:
obj=Perceptron(eta=0.01, epochs=10)

In [19]:
obj.weight

array([-3.99634175e-05, -4.01364424e-05,  1.04130274e-05])

In [25]:
X = np.ones((4,2))

In [20]:
y=np.ones((4,1))

In [27]:
obj.fit(X,y)

x with bias: 
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]
